ALTER TABLE albums ADD COLUMN IF NOT EXISTS monitored BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS monitored BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE download_jobs ADD COLUMN IF NOT EXISTS quality TEXT;

CREATE TABLE IF NOT EXISTS artist_preferences (
  artist_id INTEGER PRIMARY KEY REFERENCES artists(id) ON DELETE CASCADE,
  import_mode TEXT NOT NULL DEFAULT 'discography',
  quality TEXT NOT NULL DEFAULT '1080p',
  auto_download BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
