ALTER TABLE download_jobs ADD COLUMN IF NOT EXISTS track_id INTEGER REFERENCES tracks(id) ON DELETE SET NULL;
ALTER TABLE download_jobs ADD COLUMN IF NOT EXISTS album_id INTEGER REFERENCES albums(id) ON DELETE SET NULL;
