ALTER TABLE genres ADD COLUMN IF NOT EXISTS import_source TEXT;
ALTER TABLE genres ADD COLUMN IF NOT EXISTS import_limit INTEGER;
ALTER TABLE genres ADD COLUMN IF NOT EXISTS import_mode TEXT;
ALTER TABLE genres ADD COLUMN IF NOT EXISTS import_quality TEXT;
ALTER TABLE genres ADD COLUMN IF NOT EXISTS import_auto_download BOOLEAN;
ALTER TABLE genres ADD COLUMN IF NOT EXISTS import_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE genres ADD COLUMN IF NOT EXISTS imported_at TIMESTAMPTZ;
ALTER TABLE genres ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();
