ALTER TABLE streams
  ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS shuffle BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS encoding TEXT NOT NULL DEFAULT 'original',
  ADD COLUMN IF NOT EXISTS restarted_at TIMESTAMPTZ;
