export const loadingJokes = [
  "Warming up the hamsters. Try not to blink.",
  "Loading... because magic takes a second.",
  "Polishing pixels for your royal viewing.",
  "Fetching data from the cloud. It was napping.",
  "Still faster than you setting this up manually.",
  "If you can read this, you can wait 2 seconds.",
  "Buffering your brilliance.",
  "Starting up... please avoid touching anything.",
  "Loading... pretend this is a progress bar.",
  "Calibrating awesomeness to your standards.",
  "Spinning up servers with sheer willpower.",
  "Composing the perfect loading experience.",
  "Hang tight. The internet is being the internet.",
  "Just a moment while we summon the vibes.",
  "Hold on. We're herding electrons.",
  "Loading... try not to refresh out of boredom.",
  "Reticulating splines. Obviously.",
  "Negotiating with the database. It's stubborn.",
  "Teaching the bits to dance.",
  "Still loading. You're still watching.",
  "Optimizing the optimum. You're welcome.",
  "Waking the API from its nap.",
  "Preparing your dashboard, like it's a fine meal.",
  "Making sure the music videos behave.",
  "Ensuring everything is perfectly adequate.",
  "Crunching numbers... and your patience.",
  "One moment. We're buffering your expectations.",
  "Applying lipstick to the UI.",
  "Waiting on the universe to align.",
  "Turning it off and on again, internally.",
  "Loading... because instant is overrated.",
  "Pro tip: waiting builds character.",
  "Shuffling the bits into the right order.",
  "Finalizing everything you didn't know you needed.",
  "Checking if you really meant to open this.",
  "Still loading. Please continue existing.",
  "Linting the cosmos.",
  "Unboxing your data.",
  "Consider this a brief intermission.",
  "You could start a band while you wait.",
  "Putting the 'pro' in progress.",
  "Reheating the cache.",
  "We asked the server nicely. It should respond.",
  "Loading... because your time is our hobby.",
  "Almost there. Probably.",
  "Aligning the stars. And the CSS.",
  "Stirring the digital soup.",
  "Energizing the flux capacitor.",
  "Doing important stuff behind the curtain.",
  "Loading... don't make me tap the sign."
];

